# Site settings
title: Skythet
description: > # this means to ignore newlines until "baseurl:"
  Мақсаты белгісіз. Бірақ пайдалы және болашақта керек болады-ау деген
  мақалалар қоймасы.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: r_egemberdiev
github_username:  skythet
timezone: Asia/Almaty

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

gems:
  - jekyll-sitemap
